# Joints names
left_wheel_name: "left_wheel_joint"
right_wheel_name: "right_wheel_joint"

# I2C address of motor module
left_motor_i2c_addr: "0x0C"
right_motor_i2c_addr: "0x0A"

# Radians per tick (encoder)
left_rpt: 0.0628
right_rpt: 0.0628